---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${DEMODRA_API_REPO}
  triggers:
  - type: commit
  properties:
  - name: LOGICAL_APP_NAME
    value: ${LOGICAL_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: master
    type: text
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v4.2/bin:$PATH
      npm install
      grunt dev-setup --no-color
  - name: Unit Test and Code Coverage
    type: tester
    enable_tests: true
    test_file_pattern: ./mochatest.xml
    coverage_type: istanbul
    coverage_directory: ./tests/coverage/reports/lcov-report
    coverage_file_pattern: ./tests/coverage/reports/coverage.json
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v4.2/bin:$PATH
      npm install
      npm install -g grunt-idra3

      set +e
      grunt dev-test-cov --no-color
      grunt_result=$?
      set -e

      idra --publishtestresult --filelocation=./mochatest.xml --type=unittest
      idra --publishtestresult --filelocation=./tests/coverage/reports/coverage-summary.json --type=code

      if [ $grunt_result -ne 0 ]; then
         exit $grunt_result
      fi
- name: STAGING
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  - name: LOGICAL_APP_NAME
    value: ${LOGICAL_APP_NAME}
    type: text
  - name: LOGICAL_ENV_NAME
    value: STAGING
    type: text
  - name: BUILD_PREFIX
    value: master
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${STAGING_REGION_ID}
      organization: ${STAGING_ORG_NAME}
      space: ${STAGING_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      # Push app
      export CF_APP_NAME="staging-$CF_APP"
      cf push "${CF_APP_NAME}" -n ${CF_APP_NAME}
      export APP_URL=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
  - name: FVT Test
    type: tester
    enable_tests: true
    test_file_pattern: ./mochafvt.xml
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v4.2/bin:$PATH
      npm install
      npm install -g grunt-idra3

      set +e
      grunt fvt-test --no-color
      grunt_result=$?
      set -e

      idra --publishtestresult --filelocation=./mochafvt.xml --type=fvt

      if [ $grunt_result -ne 0 ]; then
         exit $grunt_result
      fi
- name: GATE
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: LOGICAL_APP_NAME
    value: ${LOGICAL_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: master
    type: text
  jobs:
  - name: Gate
    type: tester
    extension_id: ibm.devops.services.pipeline.dra_devops_gate
    CRITERIA: Weather Unit Test, Code Coverage, and FVT Checks
