---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${DEMODRA_API_REPO}
  triggers:
  - type: commit
  properties:
  - name: LOGICAL_APP_NAME
    value: ${LOGICAL_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: master
    type: text
  - name: IBM_CLOUD_API_KEY
    value: ${INSIGHTS_API_KEY}
    type: secure
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      npm install

      grunt dev-setup --no-color
      grunt_result=$?

      build_status="pass"
      if [ $grunt_result -ne 0 ]; then
         build_status="fail"
      fi

      # need to set the ibmcloud api for staging env. The value defaults to cloud.ibm.com
      export match=`echo $IDS_URL | grep stage`
      if [ $match ]; then
          ibmcloud api test.cloud.ibm.com
      fi

      ibmcloud plugin install doi -f -v 0.0.6
      ibmcloud login --apikey $IBM_CLOUD_API_KEY --no-region
      ibmcloud doi publishbuildrecord --branch=$GIT_BRANCH --repositoryurl=$GIT_URL --commitid=$GIT_COMMIT --status=$build_status
  - name: Unit Test and Code Coverage
    type: tester
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      npm install

      set +e
      grunt dev-test-cov --no-color
      grunt_result=$?
      set -e

      # need to set the ibmcloud api for staging env. The value defaults to cloud.ibm.com
      export match=`echo $IDS_URL | grep stage`
      if [ $match ]; then
          ibmcloud api test.cloud.ibm.com
      fi

      ibmcloud plugin install doi -f -v 0.0.6
      ibmcloud login --apikey $IBM_CLOUD_API_KEY --no-region
      ibmcloud doi publishtestrecord --filelocation=./mochatest.json --type=unittest
      ibmcloud doi publishtestrecord --filelocation=./tests/coverage/reports/coverage-summary.json --type=code

      if [ $grunt_result -ne 0 ]; then
         exit $grunt_result
      fi
- name: STAGING
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  - name: LOGICAL_APP_NAME
    value: ${LOGICAL_APP_NAME}
    type: text
  - name: LOGICAL_ENV_NAME
    value: STAGING
    type: text
  - name: BUILD_PREFIX
    value: master
    type: text
  - name: IBM_CLOUD_API_KEY
    value: ${INSIGHTS_API_KEY}
    type: secure
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${STAGING_REGION_ID}
      organization: ${STAGING_ORG_NAME}
      space: ${STAGING_SPACE_NAME}
      application: ${CF_APP_NAME}
      api_key: ${API_KEY}
    script: |
      #!/bin/bash
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH

      # Push app
      export CF_APP_NAME="staging-$CF_APP"
      cf push "${CF_APP_NAME}"
      push_result=$?
      export APP_URL=https://$(cf app $CF_APP_NAME | grep -e urls: -e routes: | awk '{print $2}')
      # View logs
      #cf logs "${CF_APP_NAME}" --recent

      deploy_status="pass"
      if [ $push_result -ne 0 ]; then
         deploy_status="fail"
      fi

      # need to set the ibmcloud api for staging env. The value defaults to cloud.ibm.com
      export match=`echo $IDS_URL | grep stage`
      if [ $match ]; then
          ibmcloud api test.cloud.ibm.com
      fi

      ibmcloud plugin install doi -f -v 0.0.6
      ibmcloud login --apikey $IBM_CLOUD_API_KEY --no-region
      ibmcloud doi publishdeployrecord --env=$LOGICAL_ENV_NAME --status=$deploy_status --joburl=$APP_URL
  - name: FVT Test
    type: tester
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      npm install

      set +e
      grunt fvt-test --no-color
      grunt_result=$?
      set -e

      # need to set the ibmcloud api for staging env. The value defaults to cloud.ibm.com
      export match=`echo $IDS_URL | grep stage`
      if [ $match ]; then
          ibmcloud api test.cloud.ibm.com
      fi

      ibmcloud plugin install doi -f -v 0.0.6
      ibmcloud login --apikey $IBM_CLOUD_API_KEY --no-region
      ibmcloud doi publishtestrecord --filelocation=./mochafvt.json --type=fvt

      if [ $grunt_result -ne 0 ]; then
         exit $grunt_result
      fi
- name: GATE
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: LOGICAL_APP_NAME
    value: ${LOGICAL_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: master
    type: text
  - name: IBM_CLOUD_API_KEY
    value: ${INSIGHTS_API_KEY}
    type: secure
  jobs:
  - name: Gate
    type: tester
    script: |-
      #!/bin/bash

      # need to set the ibmcloud api for staging env. The value defaults to cloud.ibm.com
      export match=`echo $IDS_URL | grep stage`
      if [ $match ]; then
         ibmcloud api test.cloud.ibm.com
      fi

      ibmcloud plugin install doi -f -v 0.0.6
      ibmcloud login --apikey $IBM_CLOUD_API_KEY --no-region
      ibmcloud doi evaluategate --policy "Weather Unit Test, Code Coverage, and FVT Checks" --forcedecision
- name: PRODUCTION
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  - name: LOGICAL_APP_NAME
    value: ${LOGICAL_APP_NAME}
    type: text
  - name: LOGICAL_ENV_NAME
    value: PRODUCTION
    type: text
  - name: BUILD_PREFIX
    value: master
    type: text
  - name: IBM_CLOUD_API_KEY
    value: ${INSIGHTS_API_KEY}
    type: secure
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
      api_key: ${API_KEY}
    script: |
      #!/bin/bash
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH

      # Push app
      export CF_APP_NAME="$CF_APP"
      cf push "${CF_APP_NAME}"
      push_result=$?
      export APP_URL=https://$(cf app $CF_APP_NAME | grep -e urls: -e routes: | awk '{print $2}')
      # View logs
      #cf logs "${CF_APP_NAME}" --recent

      deploy_status="pass"
      if [ $push_result -ne 0 ]; then
         deploy_status="fail"
      fi

      # need to set the ibmcloud api for staging env. The value defaults to cloud.ibm.com
      export match=`echo $IDS_URL | grep stage`
      if [ $match ]; then
          ibmcloud api test.cloud.ibm.com
      fi

      ibmcloud plugin install doi -f -v 0.0.6
      ibmcloud login --apikey $IBM_CLOUD_API_KEY --no-region
      ibmcloud doi publishdeployrecord --env=$LOGICAL_ENV_NAME --status=$deploy_status --joburl=$APP_URL
